config/routes.rb
VendingMachine::Application.routes.draw do  
  resources :machines
  root to: 'machines#index', as: 'machines'
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  attr_accessible :coca_cole, :sandwich, :snickers, :value, :water, :change

 def add_available_change(amount)
  self.change = self.change + amount
  self.save
 end

  def add_coins(amount)
		self.value = self.value + amount
    self.change = self.change + amount
		self.save
	end

	def add_stock(stock_item)
		if stock_item=="water_restock"
			self.water= self.water + 5
			self.save 
		elsif stock_item=="coca_cole_restock"
			self.coca_cole= self.coca_cole + 5
  		self.save
		elsif stock_item=="sandwich_restock"
			self.sandwich= self.sandwich + 5
  		self.save
		elsif stock_item=="snickers_restock"
			self.snickers= self.snickers + 5
  		self.save
  	end
  end

	def purchase(item,price)
		if item=="water"
			if self.value < price.to_f
        return "Please add more coins."
      elsif self.water < 1
        "The item is out of stock. Please choose another."
     	else
        self.change = self.change + price.to_f - self.value
    		self.value = self.value - price.to_f
    		self.water = self.water - 1
    		@message="You just bought a bottle of Water and your change are #{self.value}"
    		self.value=0;
  	    self.save
  	    return @message
  		end

    elsif item=="snickers"
			if self.value < price.to_f 
        return "Please add more coins."
      elsif self.snickers < 1
        "The item is out of stock. Please choose another."
     	else
        self.change = self.change + price.to_f - self.value
        self.value = self.value - price.to_f
        self.snickers = self.snickers - 1
      	@message="You just bought a Snickers and your change are #{self.value}"
        self.value=0
			  self.save
			  return @message
      end

		elsif item=="coca_cole"
			if self.value < price.to_f
        return "Please add more coins."
      elsif self.coca_cole < 1
      	"The item is out of stock. Please choose another."
      else
        self.change = self.change + price.to_f - self.value
  		  self.value = self.value - price.to_f
  		  self.coca_cole = self.coca_cole - 1
  		  @message="You just bought a coke and your change are #{self.value}"
  		  self.value=0
	      self.save
				return @message
     	end

		elsif item=="sandwich"
			if self.value < price.to_f
        return "Please add more coins."
      elsif self.sandwich < 1
    		"The item is out of stock. Please choose another."
     	else
        self.change = self.change + price.to_f - self.value
    		self.value = self.value - price.to_f
      	self.sandwich = self.sandwich - 1
        @message="You just bought a Sandwich and your change are #{self.value}"
        self.value=0
				self.save
				return @message
     	end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  def index
    # at first we are testing if the app runs for the first time.
    @vending = Machine.first
    if @vending.nil?
      @vending = Machine.create(water: 5, snickers: 5 , sandwich: 5 , coca_cole: 5 , value: 0, change: 2)
    end
    @vending = Machine.first
    if params[:amount]!=nil
       @vending.add_coins(params[:amount].to_f)
       redirect_to machines_url

    elsif params[:item]!=nil
      redirect_to machines_url , notice: @vending.purchase(params[:item],params[:price])

    elsif params[:restock]!=nil
      @vending.add_stock(params[:restock])
      redirect_to machines_url

    elsif params[:change]!=nil
      @vending.add_available_change(2)
      redirect_to machines_url , notice: "2 pounds were added to the current change for the Vending machine"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VendingMachine</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/machines/index.html.erb
<h2>Welcome to</h2>
<h1> online Vending Machine</h1>

<%= image_tag("illustration-featuring-a-vending-machine.jpg", :size => "250x300")  %>
<p>current amount of money: <%= @vending.value%>  £
    </br>
    current amount of change: <%= @vending.change%>  £
    </br>

    current stock of snickers: <%= @vending.snickers%> || current stock of coca-cole: <%= @vending.coca_cole%>  || current stock of sandwich: <%= @vending.sandwich%> || current stock of water bottles: <%= @vending.water%> </p>

<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h3>Coins</h3>
<div class="butto">
  <%= button_to '1p', machines_path(:amount => "0.01"), class: "btn btn-warning" %>
  <%= button_to '2p', machines_path(:amount => "0.02"), class: "btn btn-warning" %>
  <%= button_to '10p', machines_path(:amount => "0.1"), class: "btn btn-warning" %>
  <%= button_to '20p', machines_path(:amount => "0.2"), class: "btn btn-warning" %>
  <%= button_to '50p', machines_path(:amount => "0.5"), class: "btn btn-warning" %>
  <%= button_to '1 £', machines_path(:amount => "1"), class: "btn btn-warning" %>
  <%= button_to '2 £', machines_path(:amount => "2"), class: "btn btn-warning" %>
</div>
<h3>Purchase</h3>
<div class="butto">
<%= button_to 'water , 55p', machines_path(:item => "water", :price => "0.55"), class: "btn btn-success" %>
  <%= button_to 'snickers , 45p', machines_path(:item => "snickers", :price => "0.45"), class: "btn btn-success" %>
  <%= button_to 'sandwich, 1.5£', machines_path(:item => "sandwich", :price => "1.5"), class: "btn btn-success" %>
  <%= button_to 'coca cole , 1£', machines_path(:item => "coca_cole", :price => "1"), class: "btn btn-success" %>
  </div>

<br/><br/><br/>
<br/><br/><br/>

<h3>Re-Stock Sector</h3>

    <div class="butto">

  <%= button_to 'add 5 items to snickers', machines_path(:restock => "snickers_restock"), class: "btn btn-inverse" %>
  <%= button_to 'add 5 items to coca cole', machines_path(:restock => "coca_cole_restock"), class: "btn btn-inverse" %>
  <%= button_to 'add 5 items to sandwich', machines_path(:restock => "sandwich_restock"), class: "btn btn-inverse" %>
  <%= button_to 'add 5 items to water', machines_path(:restock => "water_restock"), class: "btn btn-inverse" %>
  <br/><br/>

  <%= button_to 'add £2 in 1p for change', machines_path(:change => "2"), class: "btn btn-inverse" %>
  </div>
  </br></br> </br></br>

  <p>© 2014 Berkakis I. Antonis. </p>